DjPriceCompare/DjPriceCompare/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from myapp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('register/', register, name="register"),
    path('signin/', signin, name="signin"),
    path('change-password/', change_password, name="change_password"),
    path('update-profile/', update_profile, name="update_profile"),
    path('logout-user/', logout_user, name="logout_user"),

    path('search-product/', search_product, name="search_product"),
    path('my-history/', my_history, name="my_history"),
    path('all-user/', all_user, name="all_user"),
    path('history-detail/<int:pid>/', history_detail, name="history_detail"),

    path('admin-signin/', admin_signin, name="admin_signin"),
    path('delete-user/<int:pid>/', delete_user, name="delete_user"),
    path('delete-history/<int:pid>/', delete_history, name="delete_history"),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjPriceCompare/myapp/models.py
from re import T
from django.db import models
from  django.contrib.auth.models import User

# Create your models here.
class Register(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    mobile = models.CharField(max_length=10, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)

    def __str__(self) -> str:
        return self.user.username


class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.TextField(null=True, default={'object':[]}, blank=True)
    
    # DateTimeField Giờ Việt Nam
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    
    def __str__(self) -> str:
        return self.user.username
    

DjPriceCompare/myapp/views.py
import json
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import *
from .utils import *
from django.conf import settings
from operator import itemgetter
import concurrent.futures as cf



from .models import User, Register
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.utils.translation import gettext as _
from django.contrib.auth.password_validation import validate_password

import json
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import *
from .utils import *
from django.conf import settings
from operator import itemgetter
import concurrent.futures as cf

from functools import partial





# NOTE:
# + locals() là một hàm trong Python, nó trả về một dictionary chứa tất cả các biến cục bộ hiện có


# Create your views here.
def home(request):
    '''
    Hàm home: trang chủ của website
    '''
    return render(request, "home.html", locals())

def about(request):
    '''
    Hàm about: trang giới thiệu của website
    '''
    return render(request, "about.html", locals())

def contact(request):
    '''
    Hàm contact: trang liên hệ của website
    '''
    return render(request, "contact.html", locals())


def register(request):
    '''
    Hàm register: trang đăng ký tài khoản
    '''
    if request.method == "POST":
        re = request.POST
        rf = request.FILES

        # Xác thực dữ liệu đầu vào
        errors = {}
        if not re['username']:
            errors['username'] = _("Vui lòng nhập email.")
        else:
            try:
                validate_email(re['username'])
            except ValidationError:
                errors['username'] = _("Email không hợp lệ.")
        
        if User.objects.filter(username=re['username']).exists():
            errors['username'] = _("Email này đã tồn tại.")

        if not re['first_name']:
            errors['first_name'] = _("Vui lòng nhập tên.")
        if not re['last_name']:
            errors['last_name'] = _("Vui lòng nhập họ.")
        if not re['password']:
            errors['password'] = _("Vui lòng nhập mật khẩu.")
        if not re['confirm_password']:
            errors['confirm_password'] = _("Vui lòng xác nhận mật khẩu.")
        elif re['password'] != re['confirm_password']:
            errors['confirm_password'] = _("Mật khẩu không khớp.")
            
        # Kiểm tra độ mạnh mật khẩu (Thêm vào đây)
        if 'password' not in errors: # Chỉ kiểm tra nếu không có lỗi về mật khẩu trước
            try:
                validate_password(re['password'])
            except ValidationError as e:
                # errors['password'] = '; '.join(e.messages)
                # Thông báo lỗi mật khẩu không đủ mạnh
                errors['password'] = _("Mật khẩu không đủ mạnh. Mật khẩu phải chứa ít nhất 8 ký tự, không chứa thông tin cá nhân, không chứa toàn ký tự số hoặc chữ cái.")
            
        if not re['mobile']:
            errors['mobile'] = _("Vui lòng nhập số điện thoại.")
        if not re['address']:
            errors['address'] = _("Vui lòng nhập địa chỉ.")

        if errors:
            for field, message in errors.items():
                messages.error(request, message, extra_tags=field)
            return render(request, "signup.html", locals())

        # Tạo user và register
        user = User.objects.create_user(
            username=re['username'], first_name=re['first_name'], last_name=re['last_name'], password=re['password'])
        Register.objects.create(
            user=user, address=re['address'], mobile=re['mobile'], image=rf['image'])
        messages.success(request, "Đăng ký thành công!")
        return redirect('signin')

    return render(request, "signup.html", locals())

# def register(request):
#     '''
#     Hàm register: trang đăng ký tài khoản
#     '''
#     if request.method == "POST":
#         re = request.POST
#         rf = request.FILES

#         # Kiểm tra xem email đã tồn tại hay chưa
#         if User.objects.filter(username=re['username']).exists():
#             messages.error(
#                 request, f"Email '{re['username']}' đã tồn tại. Vui lòng nhập email khác.")
#             return render(request, "signup.html", locals())

#         # Kiểm tra rỗng các trường thông tin
#         try:
#             if not re['username'] or not re['first_name'] or not re['last_name'] or not re['password'] or not re['address'] or not re['mobile'] or not rf['image']:
#                 messages.error(request, "Vui lòng điền đầy đủ thông tin")
#                 return render(request, "signup.html", locals())
#         except:
#             messages.error(request, "Vui lòng điền đầy đủ thông tin")
#             return render(request, "signup.html", locals())

#         # Nếu email chưa tồn tại, tạo user và register
#         user = User.objects.create_user(
#             username=re['username'], first_name=re['first_name'], last_name=re['last_name'], password=re['password'])
#         register = Register.objects.create(
#             user=user, address=re['address'], mobile=re['mobile'], image=rf['image'])
#         messages.success(request, "Registration Successful")
#         return redirect('signin')
#     return render(request, "signup.html", locals())

def update_profile(request):
    if request.method == "POST":
        re = request.POST
        rf = request.FILES
        try:
            image = rf['image']
            data = Register.objects.get(user=request.user)
            data.image = image
            data.save()
        except:
            pass
        user = User.objects.filter(id=request.user.id).update(
            username=re['username'], first_name=re['first_name'], last_name=re['last_name'])
        register = Register.objects.filter(user=request.user).update(
            address=re['address'], mobile=re['mobile'])
        messages.success(request, "Updation Successful")
        return redirect('update_profile')
    return render(request, "update_profile.html", locals())

# def signin(request):
#     if request.method == "POST":
#         re = request.POST
#         user = authenticate(username=re['username'], password=re['password'])
#         if user:
#             login(request, user)
#             messages.success(request, "Logged in successful")
#             return redirect('home')
#         else:
#             messages.error(
#                 request, "Thông tin không hợp lệ. Vui lòng thử lại.")

#     return render(request, "signin.html", locals())

def signin(request):
    if request.method == "POST":
        re = request.POST
        user = authenticate(username=re['username'], password=re['password'])
        if user:
            login(request, user)
            messages.success(request, "Đăng nhập thành công!")
            return redirect('home')
        else:
            messages.error(request, "Thông tin đăng nhập không hợp lệ. Vui lòng thử lại.")

    return render(request, "signin.html", locals())

def admin_signin(request):
    if request.method == "POST":
        re = request.POST
        user = authenticate(username=re['username'], password=re['password'])
        if user.is_staff:
            login(request, user)
            messages.success(request, "Logged in successful")
            return redirect('home')
    return render(request, "admin_signin.html", locals())

# def change_password(request):
#     if request.method == "POST":
#         re = request.POST
#         user = authenticate(username=request.user.username,
#                             password=re['old-password'])
#         if user:
#             if re['new-password'] == re['confirm-password']:
#                 user.set_password(re['confirm-password'])
#                 user.save()
#                 messages.success(request, "Password changed successfully")
#                 return redirect('home')
#             else:
#                 messages.success(request, "Password mismatch")
#         else:
#             messages.success(request, "Wrong password")
#     return render(request, "change_password.html", locals())

def change_password(request):
    if request.method == "POST":
        re = request.POST
        errors = {}

        user = authenticate(username=request.user.username, password=re['old-password'])
        if not user:
            errors['old-password'] = _("Mật khẩu cũ không đúng.")
        else:
            if re['new-password'] != re['confirm-password']:
                errors['confirm-password'] = _("Mật khẩu mới không khớp.")

            if 'new-password' not in errors:
                try:
                    validate_password(re['new-password'])
                except ValidationError as e:
                    errors['new-password'] = _("Mật khẩu quá yếu. Vui lòng chọn mật khẩu mạnh hơn.")
                    # errors['new-password'] = '; '.join([_(msg) for msg in e.messages])

        if errors:
            for field, message in errors.items():
                messages.error(request, message, extra_tags=field)
            return render(request, "change_password.html", locals())

        user.set_password(re['new-password'])
        user.save()
        messages.success(request, "Mật khẩu đã được thay đổi thành công!")
        return redirect('home')

    return render(request, "change_password.html", locals())

def logout_user(request):
    logout(request)
    messages.success(request, "Logout Successfully")
    return redirect('home')


def search_product(request):
    """
    Hàm search_product: trang tìm kiếm sản phẩm
    """
    dictobj = {'object': []}
    if request.method == "POST":
        re = request.POST
        name = re['search']
        if name == '':  # Nếu không nhập tên sản phẩm
            messages.error(request, "Vui lòng nhập tên sản phẩm")

DjPriceCompare/myapp/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


<main id="main">

  <!-- ======= Intro Single ======= -->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">Tạo dựng website so sánh giá cả</h1>
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="#">Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                About
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section><!-- End Intro Single-->

  <!-- ======= About Section ======= -->
  <section class="section-about">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 position-relative">
          <div class="about-img-box">
            <img src="{% static 'assets/img/slide-aboutt-1.jpg' %}" alt="" class="img-fluid">
          </div>
          <div class="sinse-box">
            <h3 class="sinse-title">So Sánh Giá
              <span></span>
              <br>2024
            </h3>
          </div>
        </div>
        <div class="col-md-12 section-t8 position-relative">
          <div class="row">
            <div class="col-md-6 col-lg-5">
              <img src="{% static 'assets/img/aboutt-2.jpg' %}" alt="" class="img-fluid">
            </div>
            <div class="col-lg-2  d-none d-lg-block position-relative">
              <div class="title-vertical d-flex justify-content-start">
                <span>PriceComparison</span>
              </div>
            </div>
            <div class="col-md-6 col-lg-5 section-md-t3">
              <div class="title-box-d">
                <h3 class="title-d">Tổng quan về
                  <span class="color-d">So Sánh</span> giá
                </h3>
              </div>
              <p class="color-text-a">
                Web so sánh giá là một công cụ trực tuyến cho phép người dùng so sánh giá cả của cùng một sản phẩm được bán trên nhiều nhà bán lẻ khác nhau. 
                Mục tiêu của các trang web này là giúp người tiêu dùng tìm được nơi bán sản phẩm với giá tốt nhất, tiết kiệm thời gian và tiền bạc.
              </p>
              <p class="color-text-a">
                Với sự phát triển của công nghệ thông tin, việc so sánh giá cả trở nên dễ dàng hơn bao giờ hết.
                Chúng tôi sử dụng công nghệ web scraping để lấy dữ liệu từ các trang web bán hàng lớn như <span style="font-style: italic;">Amazon, Điện máy xanh, ... </span>và hiển thị dữ liệu đó trên trang web của chúng tôi.
                Để giúp người dùng tiết kiệm thời gian và tiền bạc khi mua sắm.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- =======Team Section ======= -->
  <section class="section-agents section-t8">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="title-wrap d-flex justify-content-between">
            <div class="title-box">
              <h2 class="title-a">Meet Our Team</h2>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="card-box-d">
            <div class="card-img-d">
              <img src="{% static 'assets/img/team2.png' %}" style="width:400px;height:400px" alt="" class="img-d img-fluid">
            </div>
            <div class="card-overlay card-overlay-hover">
              <div class="card-header-d">
                <div class="card-title-d align-self-center">
                  <h3 class="title-d">
                    <a href="https://github.com/truongvanthong" class="link-two">Trương Văn Thông</a>
                  </h3>
                </div>
              </div>
              <div class="card-body-d">
                <div class="info-agents color-a">
                  <p>
                    <strong>Phone: </strong> 035 425 7974
                  </p>
                  <p>
                    <strong>Email: </strong> truongvantthong@gmail.com
                  </p>
                </div>
              </div>
              <div class="card-footer-d">
                <div class="socials-footer d-flex justify-content-center">
                  <ul class="list-inline">
                    <li class="list-inline-item">
                      <a href="https://www.facebook.com/vianhlagio2307" class="link-one">
                        <i class="bi bi-facebook" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="https://www.instagram.com/vianhlagio2307/" class="link-one">
                        <i class="bi bi-instagram" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="bi bi-linkedin" aria-hidden="true"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card-box-d">
            <div class="card-img-d">
              <img src="{% static 'assets/img/team3.png' %}" alt="" style="width:400px;height:400px" class="img-d img-fluid">
            </div>
            <div class="card-overlay card-overlay-hover">
              <div class="card-header-d">
                <div class="card-title-d align-self-center">
                  <h3 class="title-d">
                    <a href="https://github.com/nguyenncai" class="link-two">Nguyễn Chí Nguyện</a>
                  </h3>
                </div>
              </div>
              <div class="card-body-d">
                <div class="info-agents color-a">
                  <p>
                    <strong>Phone: </strong> 094 783 82 94
                  </p>
                  <p>
                    <strong>Email: </strong> nguyenncds@gmail.com
                  </p>
                </div>
              </div>
              <div class="card-footer-d">
                <div class="socials-footer d-flex justify-content-center">
                  <ul class="list-inline">
                    <li class="list-inline-item">
                      <a href="https://www.facebook.com/chinguyen.nguyen.169" class="link-one">
                        <i class="bi bi-facebook" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="bi bi-instagram" aria-hidden="true"></i>
                      </a>
                    </li>
                    <!-- <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="bi bi-linkedin" aria-hidden="true"></i>
                      </a>
                    </li> -->
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- <div class="col-md-4">
          <div class="card-box-d">
            <div class="card-img-d">
              <img src="{% static 'assets/img/team3.png' %}" alt="" style="width:400px;height:400px" class="img-d img-fluid">
            </div>
            <div class="card-overlay card-overlay-hover">
              <div class="card-header-d">
                <div class="card-title-d align-self-center">
                  <h3 class="title-d">
                    <a href="agent-single.html" class="link-two">Emma Toledo
                      <br> Cascada</a>
                  </h3>
                </div>
              </div>
              <div class="card-body-d">
                <p class="content-d color-text-a">
                  Sed porttitor lectus nibh, Cras ultricies ligula sed magna dictum porta two.
                </p>
                <div class="info-agents color-a">
                  <p>
                    <strong>Phone: </strong> +54 356 945234
                  </p>
                  <p>
                    <strong>Email: </strong> agents@example.com
                  </p>
                </div>
              </div>
              <div class="card-footer-d">
                <div class="socials-footer d-flex justify-content-center">
                  <ul class="list-inline">
                    <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="bi bi-facebook" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="bi bi-twitter" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="bi bi-instagram" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="bi bi-linkedin" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="bi bi-dribbble" aria-hidden="true"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div> -->
      </div>
    </div>
  </section><!-- End About Section-->

</main><!-- End #main -->
{% include 'footer.html' %}
{% endblock  %}  

DjPriceCompare/myapp/templates/all_user.html
{% include 'base.html' %}
{% load static %}
{% block body %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
 
<style>
#active {
  border-radius: 50%;
}
#inactive {
  border-radius: 50%;
}
#active:hover {
  cursor: default !important;
}
#inactive:hover {
  cursor: default !important;
}
img {
  width: 60px;
  height: 60px;
}
.table-responsive{
  font-size:11px;
}
.material-symbols-outlined
{
  font-size:14px;
}
td{ 
  padding:0px;
}
</style>

<section class="section-services section-t8">
    <div class="container">
    <h3>All User </h3><hr>
    

    <div class="table-responsive">
        <table id="example1" class="display nowrap" style="width: 100%">
            <thead>
              <tr>
                <th>#</th>
                <th>Image</th>
                <th>Email</th>
                <th>Name</th>
                <th>Mobile</th>
                <th>Address</th>
                <th style="text-align: center">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for i in data %}
              <tr>
                <td>{{i.id}}</td>
                <!-- Nếu không có ảnh thì cho ảnh mặc định -->
                {% if not i.image %}
                <td><img src="{% static 'images/aboutt-2.jpg' %}" class="img-thumbnail" style="width:100px;height:100px"/></td>
                {% else %}
                <td><img src="{{i.image.url}}" class="img-thumbnail" style="width:100px;height:100px"/></td>
                {% endif %}
                <td>{{i.user.username}}</td>
                <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                <td>{{i.mobile}}</td>
                <td>{{i.address}}</td>
                
                <td>
                  <a href="/delete-user/{{i.id}}/" title="Delete History" class="btn btn-danger" onclick="return confirm('Are your sure?')"><i class="fas fa-trash" aria-hidden="true"></i> Delete</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>

  </div>
{% include 'footer.html' %}
{% include 'tablecdn.html' %}
{% endblock  %} 

DjPriceCompare/myapp/templates/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<section class="section-services section-t8">
    <div class="container">
    <h3>Change Password</h3><hr>
    <div class="form">
      <form class="form-a" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
        <div class="row">
            <div class="col-md-12 mb-2">
                <div class="form-group">
                <label class="pb-2" for="Type">Old Password</label>
                <input type="password" class="form-control form-control-a" placeholder="Old Password" name="old-password">
                </div>
            </div>
            <div class="col-md-12 mb-2">
                <div class="form-group">
                    <label class="pb-2" for="Type">New Password</label>
                    <input type="password" class="form-control form-control-a" placeholder="New Password" name="new-password">
                </div>
            </div>
            <div class="col-md-12 mb-2">
                <div class="form-group">
                  <label class="pb-2" for="Type">Confirm Password</label>
                  <input type="password" class="form-control form-control-a" placeholder="Confirm Password" name="confirm-password">
                </div>
            </div>
          
            <div class="col-md-12">
                <button type="submit" class="btn btn-b">Submit</button>
            </div>
        </div>
      </form>
    </div>
  </div>
{% include 'footer.html' %}
{% endblock  %} 

DjPriceCompare/myapp/templates/signin.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<section class="section-services section-t8">
  <div class="container">
    <h3>User Sign In</h3>
    <hr>

    <div class="form">
      <form class="form-a" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">

          <div class="col-md-12 mb-2">
            <div class="form-group">
              <label class="pb-2" for="username">Email</label>
              <input type="email" class="form-control form-control-a" placeholder="Email" name="username" required>
            </div>
          </div>
          <div class="col-md-12 mb-2">
            <div class="form-group">
              <label class="pb-2" for="password">Password</label>
              <input type="password" class="form-control form-control-a" placeholder="Password" name="password" required>
            </div>
          </div>

          <div class="col-md-12">
            <button type="submit" class="btn btn-b">Sign In</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>

{% include 'footer.html' %}
{% endblock  %}

DjPriceCompare/myapp/templates/tablecdn.html
<link href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />








<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>




<script>
$(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
} );


$(document).ready(function() {
    $('#example1').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
} );
</script>

DjPriceCompare/myapp/templates/update_profile.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<section class="section-services section-t8">
    <div class="container">
    <h3>My Profile</h3><hr>
    <div class="form">
      <form class="form-a" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6 mb-2">
            <div class="form-group">
              <label class="pb-2" for="Type">First name</label>
              <input type="text" class="form-control form-control-a" placeholder="First Name" name="first_name" value="{{request.user.first_name}}">
            </div>
          </div>
          <div class="col-md-6 mb-2">
            <div class="form-group">
              <label class="pb-2" for="Type">Last name</label>
              <input type="text" class="form-control form-control-a" placeholder="Last Name" name="last_name" value="{{request.user.last_name}}">
            </div>
          </div>
          <div class="col-md-6 mb-2">
            <div class="form-group">
              <label class="pb-2" for="Type">Email</label>
              <input type="email" class="form-control form-control-a" placeholder="Email" name="username" value="{{request.user.username}}" readonly>
            </div>
          </div>
          {% comment %} <div class="col-md-6 mb-2">
            <div class="form-group">
              <label class="pb-2" for="Type">Password</label>
              <input type="password" class="form-control form-control-a" placeholder="Password" name="password">
            </div>
          </div> {% endcomment %}
          <div class="col-md-4 mb-2">
            <div class="form-group">
                <label class="pb-2" for="Type">Image</label>
                <input type="file" class="form-control form-control-a" name="image">
            </div>
          </div>
          <div class="col-md-2 mb-2">
            <div class="form-group">
                <img src="{% if request.user.register_set.all.0.image %}{{request.user.register_set.all.0.image.url}}{% endif %}" class="img-thumbnail">
            </div>
          </div>
          <div class="col-md-6 mb-2">
            <div class="form-group">
                <label class="pb-2" for="Type">Mobile</label>
                <input type="number" class="form-control form-control-a" name="mobile" placeholder="Mobile" value="{{request.user.register_set.all.0.mobile}}">
            </div>
          </div>
          <div class="col-md-6 mb-2">
            <div class="form-group">
              <label class="pb-2" for="bedrooms">Address</label>
              <textarea class="form-control form-control-a" name="address" placeholder="Adress in detail">{{request.user.register_set.all.0.address}}</textarea>
            </div>
          </div>
          
          <div class="col-md-12">
            <button type="submit" class="btn btn-b">Update</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% include 'footer.html' %}
{% endblock  %} 